services:
  - type: static_site
    name: smart-stock-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://your-backend-url.onrender.com
      - key: VITE_FIREBASE_API_KEY
        value: your-firebase-api-key
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: your-project.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: your-project-id
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: your-project.appspot.com
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: your-messaging-sender-id
      - key: VITE_FIREBASE_APP_ID
        value: your-app-id