#!/bin/bash

echo "🚀 Manual Railway Deployment Guide"
echo "=================================="
echo ""
echo "Since Railway CLI has limitations on your plan, follow these steps:"
echo ""
echo "1. Go to your Railway dashboard:"
echo "   https://railway.com/project/27c3e4ce-65f4-490c-a273-951c24655b1f"
echo ""
echo "2. Click 'New Service' → 'Deploy from GitHub'"
echo ""
echo "3. If you don't have a GitHub repo:"
echo "   - Go to https://github.com/new"
echo "   - Create a new repository called 'smart-stock-ordering'"
echo "   - Make it public"
echo "   - Don't initialize with README (we already have files)"
echo ""
echo "4. Push your code to GitHub:"
echo "   git remote add origin https://github.com/YOUR_USERNAME/smart-stock-ordering.git"
echo "   git push -u origin main"
echo ""
echo "5. Back in Railway:"
echo "   - Connect your GitHub repository"
echo "   - Select the repository"
echo "   - Railway will auto-detect it's a Python project"
echo ""
echo "6. Set Environment Variables in Railway dashboard:"
echo "   - DEV_MODE=false"
echo "   - FIREBASE_PROJECT_ID=your_project_id"
echo "   - FIREBASE_PRIVATE_KEY=your_private_key"
echo "   - FIREBASE_CLIENT_EMAIL=your_client_email"
echo "   - FIREBASE_CLIENT_ID=your_client_id"
echo "   - FIREBASE_PRIVATE_KEY_ID=your_private_key_id"
echo "   - FIREBASE_CLIENT_CERT_URL=your_cert_url"
echo ""
echo "7. Add Redis Add-on:"
echo "   - Click 'New Service' → 'Database' → 'Redis'"
echo "   - Railway will provide REDIS_URL automatically"
echo ""
echo "8. Deploy!"
echo "   - Railway will automatically deploy your backend"
echo "   - You'll get a URL like: https://your-app-name.railway.app"
echo ""
echo "9. For Frontend:"
echo "   - Create another service for the frontend"
echo "   - Use Vercel, Netlify, or Railway static hosting"
echo ""
echo "✅ Your app will be live!" 