#!/bin/bash

echo "🚀 Step-by-Step Railway Deployment Guide"
echo "========================================"
echo ""

echo "📋 STEP 1: Create GitHub Repository"
echo "-----------------------------------"
echo "1. Go to: https://github.com/new"
echo "2. Repository name: smart-stock-ordering"
echo "3. Make it PUBLIC"
echo "4. DON'T initialize with README"
echo "5. Click 'Create repository'"
echo "6. Copy the repository URL (e.g., https://github.com/YOUR_USERNAME/smart-stock-ordering.git)"
echo ""

echo "📋 STEP 2: Push Code to GitHub"
echo "------------------------------"
echo "After creating the repository, run these commands:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/smart-stock-ordering.git"
echo "git push -u origin main"
echo ""

echo "📋 STEP 3: Deploy to Railway"
echo "----------------------------"
echo "1. Go to: https://railway.com/project/27c3e4ce-65f4-490c-a273-951c24655b1f"
echo "2. Click 'New Service'"
echo "3. Choose 'Deploy from GitHub'"
echo "4. Connect your GitHub account"
echo "5. Select 'smart-stock-ordering' repository"
echo "6. Railway will auto-detect it's a Python project"
echo ""

echo "📋 STEP 4: Set Environment Variables"
echo "-----------------------------------"
echo "In your Railway service dashboard:"
echo "1. Go to 'Variables' tab"
echo "2. Add these variables:"
echo "   - DEV_MODE=false"
echo "   - FIREBASE_PROJECT_ID=your_project_id"
echo "   - FIREBASE_PRIVATE_KEY=your_private_key"
echo "   - FIREBASE_CLIENT_EMAIL=your_client_email"
echo "   - FIREBASE_CLIENT_ID=your_client_id"
echo "   - FIREBASE_PRIVATE_KEY_ID=your_private_key_id"
echo "   - FIREBASE_CLIENT_CERT_URL=your_cert_url"
echo ""

echo "📋 STEP 5: Add Redis Database"
echo "-----------------------------"
echo "1. In Railway dashboard, click 'New Service'"
echo "2. Choose 'Database' → 'Redis'"
echo "3. Railway will automatically provide REDIS_URL"
echo ""

echo "📋 STEP 6: Get Your App URL"
echo "---------------------------"
echo "1. Click on your 'unable-thunder' service"
echo "2. Look for 'Domains' section"
echo "3. Copy the URL (e.g., https://unable-thunder-production-xxxx.up.railway.app)"
echo ""

echo "📋 STEP 7: Test Your Deployment"
echo "-------------------------------"
echo "Test these endpoints:"
echo "- Health: https://your-url.railway.app/health"
echo "- API Docs: https://your-url.railway.app/docs"
echo "- Root: https://your-url.railway.app/"
echo ""

echo "🎉 Your app will be live!"
echo ""
echo "Need help? Run: ./test_railway_deployment.sh" 