services:
  - type: web
    name: smart-stock-ordering-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    rootDir: backend
    envVars:
      - key: DEV_MODE
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0 