services:
  - type: web
    name: smart-stock-ordering-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python app.py"
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
  
  - type: web
    name: smart-stock-ordering-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run preview -- --host 0.0.0.0 --port $PORT"
    plan: free
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: PORT
        value: 10000 