services:
  - type: web
    name: smart-stock-ordering-backend
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT
    rootDir: backend
    envVars:
      - key: DEV_MODE
        value: false
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1" 